# Generated by Django 2.0.8 on 2019-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enum',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Incomplete'), (1, 'Proposed'), (3, 'Draft'), (6, 'Approved')], default=1),
        ),
    ]
