# Generated by Django 2.0.8 on 2019-02-01 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Updated Date')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('ordering', models.CharField(default='0', max_length=10)),
                ('notes', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('notes_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30)),
                ('_notes_rendered', models.TextField(editable=False, null=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_enum_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering', 'ref'],
            },
        ),
        migrations.CreateModel(
            name='EnumDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Updated Date')),
                ('language', models.CharField(max_length=2)),
                ('culture', models.CharField(max_length=5)),
                ('display', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('notes_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30)),
                ('_notes_rendered', models.TextField(editable=False, null=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_enumdisplay_creator', to=settings.AUTH_USER_MODEL)),
                ('enum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Enum')),
                ('updator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_enumdisplay_updator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Updated Date')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deprecated'), (1, 'Proposed'), (3, 'Draft'), (6, 'Approved')], default=1)),
                ('notes', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('notes_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30)),
                ('_notes_rendered', models.TextField(editable=False, null=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_enumtype_creator', to=settings.AUTH_USER_MODEL)),
                ('updator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_enumtype_updator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enum',
            name='enumtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.EnumType'),
        ),
        migrations.AddField(
            model_name='enum',
            name='updator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_enum_updator', to=settings.AUTH_USER_MODEL),
        ),
    ]
